### DISCUSSION TITLE
Add guide triggers to fields, blocks (neo / matrix) and heading UI elements

### DISCUSSION THREAD

**Discussion by leevigraham** [wbrowar/craft-3-guide#112] [Ideas and Feature Requests]
Hi @wbrowar,

I'm evaluating guide and thought it would be nice to have guide triggers assigned to fields, blocks (neo / matrix) and heading UI elements to provide more context specific guides.

### Field example: 

Label: 

![image](https://github.com/user-attachments/assets/790b1b0f-b6a1-43e3-ab94-b8894d46699e)

No Label: 

![image](https://github.com/user-attachments/assets/a52ab766-1983-4b54-ac8e-2220efeb9ce6)

### Heading UI element example:

![image](https://github.com/user-attachments/assets/04b62a5a-7d8c-4e86-8892-54ca96e193a2)

### Neo

This one could be a bit more interesting… options could include a new "tab" that opens the slide out.

![image](https://github.com/user-attachments/assets/032fde89-4e41-4eec-b344-be84ecf24bc9)

or as a drop down item:

![image](https://github.com/user-attachments/assets/f64c75cb-9d6d-4712-ac69-12a8ca7bbc1b)

----

If https://github.com/wbrowar/craft-guide/issues/106 was implemented this could cover matrix and neo blocks… a new tab could have the guide in the tab content… although I think this would still be better as a slide out to keep the implementation consistent.

**Comment by wbrowar** [comment]
Hey @leevigraham! Thanks for all of the ideas here. I've already started working on #106 and I think you're right that it should cover some of this, but let me digest this for a little bit and see if I can come up with some ways to address your ideas here.

**Comment by wbrowar** [comment]
@leevigraham, I've been making pretty good progress on the field header portion of this. I'm still working on the UI portion to set this up, but my thought is you can attach a guide to a field and wherever that field is used you'll find a button that pops the guide out in a slideout. Does that sound in line with what you're looking for?

Here's what it looks like when I set attach a guide to the Body and Text fields.

<img width="667" alt="Screenshot 2024-11-21 at 12 19 54 PM" src="https://github.com/user-attachments/assets/a44b72b1-b7ed-456d-b0d1-e991a5dd04ab">

<img width="667" alt="Screenshot 2024-11-21 at 12 20 00 PM" src="https://github.com/user-attachments/assets/cede0bf7-9bd8-480b-9936-2c7e7f7b5984">

I haven't pushed this branch up, but when I do I'll post an update here with the composer version to try.

**Reply by wbrowar** [reply]
So the one thing I'm trying to figure out is how to tie a guide to a field and whether or not to worry about field instances. My thought is that one guide should be tied to a field and that guide should be shown everywhere the field is used, but it would mean you'd want to keep whatever content you put into the guide generic enough that it can work from entry type to entry type.

I was thinking about ways to override this in field instances or to pull in the context of where the field is placed so you can change the guide content based on that, but I think both make this more complicated. I think if you want to describe something that is very specific to where a field is used, maybe that should go into another guide on that edit page or in a UI element on that content type.

Still thinking about it.

**Comment by wbrowar** [comment]
Hi @leevigraham, if you'd like to take a look at the current setup, you can test it out with this version:

```
"wbrowar/guide": "5.2.0.x-dev"
```

I'm not opposed to this current setup, but I'd like to know what you think about the field settings and the way it displays the buttons next to the headers. I think this will be helpful, but unlike the UI Elements and the guides on entry edit pages, there's no context here because of the way the buttons are added to the field headers.

Here's a link to the docs for this feature:
https://github.com/wbrowar/craft-guide/blob/5.2.0/src/templates/docs/en/guide-organizer.md#fields

**Comment by wbrowar** [comment]
Hi @leevigraham, 5.2 is out now and it includes the field header buttons and the UI Element preset features. I am still thinking about the Neo stuff and will poke around in Neo to see what can be done.

**Reply by leevigraham** [reply]
Nice… sorry I didn't get to give more feedback. I've been snowed under. The only quick feedback I have from the screenshots above is that the guide icon on fields should be less obvious. I know it sounds weird but it shouldn't add more complexity to the UI. I liked the idea of just the little grey icon.

**Reply by wbrowar** [reply]
Hi @leevigraham, Sorry I didn't respond about this earlier. My thought is that this isn't something that should be a feature in Guide in order to make the button look that way, but because those blue buttons are all plain HTML on the page you can use CSS to style them.

You can use another guide to put CSS throughout the CP (just like you would in a module or using something like CP CSS). Here's how I would do this:

1. Create a new guide and name it whatever you'd like.
2. Add the following CSS into the CSS field and save it:

```css
.field .heading guide-slideout-button {
    & button {
        padding: 0 !important;
        background: transparent;
        color: var(--guide-color-blue);

        &:hover {
            color: color-mix(in srgb, var(--guide-color-blue), black 40%);
        }

        & svg {
            aspect-ratio: 1;
            width: 1.4em;
            height: auto;
        }
        /* Taken styles from the .visually-hidden class */
        & > span {
            height: 1px;
            margin: -1px;
            overflow: hidden;
            padding: 0;
            position: absolute;
            width: 1px;
            clip: rect(0, 0, 0, 0);
            border-width: 0;
            white-space: nowrap;
        }
    }
}
```

3. Go to the Guide Organizer page and scroll down to the **Control Panel Pages** section. Add your new guide and for the first field set the URI patter to `*`. For the selector field pick any selector you'd like—even `body` works here.

This will put this guide on all pages across the CP and since it's just CSS and nothing is getting rendered to the page you can add more CSS to adjust other things in the CP.
